---
jobs:
  clangformat:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: clangformat-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          filter: tree:0
      - name: Lint c++ code
        uses: ./
        with:
          run: >
            python tools/g_ls_tree.py cpp h hpp |
            xargs --no-run-if-empty --null --
            clang-format --dry-run -style=file -Werror
  corpus-retest:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: corpus-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: true
      - env:
          GITHUB_REF: ${{ github.ref }}
        name: Corpus recheck
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/corpus_retest.py build "${GITHUB_REF}"
      - continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: corpus-${{ github.run_id }}-retest
          commit_message: Update fuzzing corpus.
          create_branch: true
          file_pattern: unit_tests/fuzz
          repository: ${{ github.workspace }}
  debug:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: debug-${{ github.workflow }}-${{ github.ref }}
    env:
      CXXFLAGS: -O0 -g -pedantic -DDEBUG -Wall -Wdeprecated -Werror -Wextra -Wpedantic
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          filter: tree:0
          submodules: true
      - name: Run tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py
  libcpp:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: libcpp-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          filter: tree:0
          submodules: true
      - env:
          CMAKE_BUILD_TYPE: RelWithDebInfo
          CXXFLAGS: -stdlib=libc++
        name: Basic unit tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py
  release:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: release-${{ github.workflow }}-${{ github.ref }}
    env:
      CMAKE_BUILD_TYPE: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          filter: tree:0
          submodules: true
      - name: Run tests
        uses: ./
        with:
          run: |
            rustup default stable
            python tools/cmake_ninja.py
  rustformat:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: rustformat-${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          filter: tree:0
      - name: Lint rust code
        uses: ./
        with:
          run: >
            rustup default stable &&
            find . -name Cargo.toml
            -exec cargo fmt --all --check --manifest-path '{}' --verbose ';'

name: CMake

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .clang-format
      - .github/workflows/cmake.yml
      - "**.cpp"
      - "**.h"
      - "**.hpp"
      - "**.py"
      - "**/*.rs"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - cmake/**
      - CMakeLists.txt
      - external/**
      - oxidation/**
      - unit_tests/fuzz/cases.json
  workflow_dispatch: ~
