---
jobs:
  trufflehog:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: TruffleHog OSS Workflow Dispatch
        uses: trufflesecurity/trufflehog@v3.78.1
        with:
          base: ${{ inputs.baseRef }}
          extra_args: --only-verified
          head: HEAD
          path: ./
      - if: ${{ github.event_name == 'push' }}
        name: TruffleHog OSS Push
        uses: trufflesecurity/trufflehog@v3.78.1
        with:
          # yamllint disable-line rule:line-length
          base: ${{ github.ref != 'refs/heads/stable' && github.event.repository.default_branch || 'HEAD^' }}
          extra_args: --only-verified
          head: HEAD
          path: ./
name: TruffleHog
# yamllint disable-line rule:truthy
on:
  push: ~
  workflow_dispatch:
    inputs:
      baseRef:
        default: ""
        description: Base branch to compare against
        required: false
