---
jobs:
  utf8_generate:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          filter: tree:0
      - name: generate utf8 grammar
        uses: ./
        with:
          run: >
            find tools -name 'generate_utf8_*.py' -not -name '*insane*' -print0 |
            xargs --no-run-if-empty --null -n1 -P3 --
            /opt/edge-virtualenv/bin/python;
            python tools/g_ls_tree.py hpp |
            xargs --no-run-if-empty --null --
            clang-format -style=file -i
      - continue-on-error: true
        if: github.ref == 'refs/heads/stable'
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: utf8-generate-grammar
          commit_message: Update utf8 grammar.
          create_branch: true
          file_pattern: library/grammar
          repository: ${{ github.workspace }}

name: Utf8 Generate

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/utf8-generate.yml
      - tools/generate_utf8_*.py
  workflow_dispatch: ~
