---
jobs:
  yamllint:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          filter: tree:0
      - name: Lint yaml code
        uses: ./
        with:
          run: >
            python tools/g_ls_tree.py yml yaml |
            xargs --no-run-if-empty --null --
            yamllint -f github

name: YamlLint

# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - .github/workflows/yamllint.yml
      - "**.yml"
  workflow_dispatch: ~
